# @package _group_
name: caf
prepare: null
copy: null
gen: null
compile: null
run: ["${savina_path}/build/bin/${benchmark.targets.caf.bin}",
      "--scheduler.max-threads=${threads}",
      "--iterations=${iterations}",
      "${args:benchmark.targets.caf.run_args}"]
parser:
  _target_: "parser.parse_caf_output"
